remote_theme: KevinWMatthews/minima
title: c/led_on
description:
  Test-drive a fake hardware interface with CppUTest.
  Configure with CMake.
  Run with Docker.
author: Kevin W Matthews
author_url: https://www.kevinwmatthews.com
header_pages:
  - source-code.md
